language: ruby

before_script:
  - mongo braumeister-test --eval 'db.addUser("braumeister", "braumeister");'

branches:
  except:
    - production
    - staging

rvm:
 - 1.9.3
 - jruby-19mode
 - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head
  exclude:
    - rvm:     1.9.3
      gemfile: Gemfile.ruby-head
    - rvm:     jruby-19mode
      gemfile: Gemfile.ruby-head
    - rvm:     ruby-head
      gemfile: Gemfile

services: mongodb
