language: ruby

before_script:
  - mongo braumeister-test --eval 'db.addUser("braumeister", "braumeister");'
  - sed -i '2d' Gemfile

branches:
  except:
    - production
    - staging

gemfile: Gemfile.travis

rvm:
 - 1.9.3
 - 2.0.0
 - jruby-19mode
 - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head

services: mongodb
