language: ruby

before_install:
  - sed -i '2d' Gemfile

before_script:
  - mongo braumeister-test --eval 'db.addUser("braumeister", "braumeister");'

branches:
  except:
    - production
    - staging

rvm:
 - 2.1.0
 - jruby-head
 - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

services: mongodb
