language: ruby
sudo: false

before_install:
  - sed -i '2d' Gemfile

before_script:
  - mongo braumeister-test --eval 'db.addUser("braumeister", "braumeister");'

after_success:
  - bundle exec codeclimate-test-reporter

branches:
  except:
    - production
    - staging

cache: bundler

rvm:
 - 2.4.1
 - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/05a6d2ff3a4a9c33343f

services: mongodb
