development:
  uri: mongodb://braumeister:braumeister@localhost:27017/braumeister

production:
  uri: <%= ENV['MONGOLAB_URI'] %>

test:
  uri: mongodb://braumeister:braumeister@localhost:27017/braumeister
