development:
  clients:
    default:
      database: braumeister
      hosts:
        - localhost:27017
      options:
        user: braumeister
        password: braumeister

production:
  clients:
    default:
      database: <%= ENV['MONGOLAB_DB'] %>
      hosts:
        - <%= ENV['MONGOLAB_HOST'] %>
      options:
        max_pool_size: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
        user: <%= ENV['MONGOLAB_USERNAME'] %>
        password: <%= ENV['MONGOLAB_PASSWORD'] %>

test:
  clients:
    default:
      database: braumeister-test
      hosts:
        - localhost:27017
      options:
        user: braumeister
        password: braumeister
