development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: braumeister
      username: braumeister
      password: braumeister
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: braumeister-test
      username: braumeister
      password: braumeister
