development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: braumeister
      username: braumeister
      password: braumeister

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: braumeister-test
      username: braumeister
      password: braumeister
