---
<%= ENV["RAILS_ENV"] %>:
  ssl: false
  monitor_mode: true
  license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  developer_mode: false
  app_name: <%= ENV["NEW_RELIC_APPNAME"] %>
  capture_params: true
  log_level: warn
  background:
    monitor_mode: true
